# Generated by Django 3.1.7 on 2021-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=39)),
                ('pcat', models.CharField(choices=[('Electronics', 'Electronics'), ('Household', 'Household'), ('Grocerry', 'Grocerry'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Books', 'Books')], max_length=38)),
                ('pqty', models.IntegerField()),
                ('pprice', models.FloatField()),
                ('ppayment', models.CharField(choices=[('COD', 'COD'), ('Prepaid', 'Prepaid')], max_length=37)),
                ('pseller', models.CharField(choices=[('Amazone', 'Amazone'), ('Flipcart', 'Flipcart'), ('Myntra', 'Myntra'), ('Ebay', 'Ebay'), ('Snapdeal', 'Snapdeal')], max_length=43)),
                ('pstatus', models.CharField(choices=[('Recieved', 'Recieved'), ('Pending', 'Pending'), ('Delievered', 'Delievered')], max_length=42)),
            ],
        ),
    ]
